export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const SET_ARTICLES = "SET_ARTCILES";
export const SET_PAGE_NUMBERS = "SET_PAGE_NUMBERS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"